### ISSUE TITLE
readthedocs fails to correctly generate links to module functions 

### ISSUE THREAD

**Issue by decarlof** [xray-imaging/DMagic#1]
If I make html on the local clone of the repository all works but the redthedocs auto built fails to create the links to the module functions: 

http://img-data-management.readthedocs.org/en/latest/source/api/data_management.scheduling.html

not sure how to fix it ...

**Comment by dgursoy** [comment]
#2 should solve this. RTD will be able to install dependencies from requirements.txt.

**Comment by decarlof** [comment]
fixed
